### ISSUE TITLE
Error in rule combinedout

### ISSUE THREAD

**Issue by timeresistance1996** [NeLLi-team/gvclass#1]
Dear Dr. Frederik Schulz，
    Thanks for your code and pipeline! I am try with your gaven example files. Every steps run successful until ’rule combinedout‘. The following is the complete error log：

[Tue Mar 14 13:09:46 2023]
rule combinedout:
    input: example/results/PkV-RF01/PkV-RF01.summary.tab, example/results/AC3300027503___Ga0255182_1000024/AC3300027503___Ga0255182_1000024.summary.tab
    output: example/results/gvclass_out.tab
    jobid: 2
    reason: Missing output files: example/results/gvclass_out.tab
    resources: tmpdir=/tmp

example/results/AC3300027503___Ga0255182_1000024/AC3300027503___Ga0255182_1000024.summary.tab is empty
example/results/PkV-RF01/PkV-RF01.summary.tab is empty
Traceback (most recent call last):
  File "workflow/scripts/10combinedout.py", line 35, in <module>
    main()
  File "/root/anaconda3/envs/ncldv/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/envs/ncldv/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/envs/ncldv/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/envs/ncldv/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "workflow/scripts/10combinedout.py", line 21, in main
    df_results_f = pd.concat(results, axis=0, ignore_index=True)
  File "/root/anaconda3/envs/ncldv/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    sort=sort,
  File "/root/anaconda3/envs/ncldv/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[Tue Mar 14 13:09:46 2023]
Error in rule combinedout:
    jobid: 2
    input: example/results/PkV-RF01/PkV-RF01.summary.tab, example/results/AC3300027503___Ga0255182_1000024/AC3300027503___Ga0255182_1000024.summary.tab
    output: example/results/gvclass_out.tab
    shell:
        source  /root/anaconda3/bin/activate ncldv
    python workflow/scripts/10combinedout.py -r example/results/ -o example/results/gvclass_out.tab
    touch example/results/gvclass_out.tab
    
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-03-14T130945.494854.snakemake.log

I have ckecked that both example/results/PkV-RF01/PkV-RF01.summary.tab and example/results/AC3300027503___Ga0255182_1000024/AC3300027503___Ga0255182_1000024.summary.tab is exist but empty.

Do you have any idea how to solve it？

**Comment by fschjgi** [comment]
Fixed a potential issue in 01predict.py that may have prevented output from being created. It should work now as expected on the example dir. There will be another major update to gvclass later this week or early next week after we finalized the benchmarking.

**Comment by timeresistance1996** [comment]
I'm sorry to disturb you again. 
May I ask if your updating is complete. I still got the same error when run with the updated 01predict.py.

**Comment by fschjgi** [comment]
Thanks for following-up. We did not push the latest changes yet but were not able to reproduce the error you describe with the current version.

1) Please delete the old version and clone the entire repository (not just the updated 01predict.py) cd into the cloned directory and try again to run it with the example command.

2) If  it still does not work, please provide info about the system you are using, conda and snakemake versions and also check the log files in the output directory and snakemake log file to see if there is any other error message.

**Comment by timeresistance1996** [comment]
I have cloned all update directory indeed but nothing changed. 
My conda version is 4.12.0 with 20.04.1-Ubuntu system. version of snakemake is 7.24.0.

In my opinion, the steps before ’rule combinedout‘ were successfully run. 
Here is the complete log:

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Job stats:
job            count    min threads    max threads
-----------  -------  -------------  -------------
all                1              1              1
cleanup            2              1              1
combinedout        1              1              1
total              4              1              1

Select jobs to execute...

[Sun Mar 26 21:14:03 2023]
rule combinedout:
    input: example/results/PkV-RF01/PkV-RF01.summary.tab, example/results/AC3300027503___Ga0255182_1000024/AC3300027503___Ga0255182_1000024.summary.tab
    output: example/results/gvclass_out.tab
    jobid: 2
    reason: Missing output files: example/results/gvclass_out.tab
    resources: tmpdir=/tmp

[Sun Mar 26 21:14:40 2023]
Error in rule combinedout:
    jobid: 2
    input: example/results/PkV-RF01/PkV-RF01.summary.tab, example/results/AC3300027503___Ga0255182_1000024/AC3300027503___Ga0255182_1000024.summary.tab
    output: example/results/gvclass_out.tab
    shell:
        source  /root/anaconda3/bin/activate ncldv
    python workflow/scripts/10combinedout.py -r example/results/ -o example/results/gvclass_out.tab
    touch example/results/gvclass_out.tab
    
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-03-26T211317.145613.snakemake.log

**Comment by fschjgi** [comment]
We are unable to reproduce the issue (gvclass is working for us as expected on different systems / setups including Ubuntu, Fedora, Manjaro, Chromebook - but it is not working on Macbook M1). In case output has been generated from one of the previous runs the file will exist even if emtpy (if run with the old version), depending on the dir structure you are using this might explain the issue. Could you exit the cloned directory and run the following steps:

```
mamba create -c conda-forge -c bioconda -n snk snakemake   # for testing purpose make sure the env only contains snakemake
conda activate snk  # activate the env
rm -rf gvclass # delete the old gvclass dir including the example dir and the hidden .snakemake dir
git clone https://github.com/NeLLi-team/gvclass.git # clone it again
cd gvclass # run the snakemake from within the cloned dir
snakemake -j  8 --use-conda --config querydir="example"  # example command
```
In case it still does not work please send me the "example/results" and the .snakemake/log dirs so that I can check the detailed output. 

We are also working on a new docker version of gvclass and update the repo later this week which might solve any potential issue with snakemake.

**Comment by timeresistance1996** [comment]
Here is the example/results files.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NeLLi-team/gvclass"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 凌晨0:35
***@***.***&gt;;
抄送:&nbsp;"Time ***@***.******@***.***&gt;;
主题:&nbsp;Re: [NeLLi-team/gvclass] Error in rule combinedout (Issue #1)





 
We are unable to reproduce the issue (gvclass is working for us as expected on different systems / setups including Ubuntu, Fedora, Manjaro, Chromebook - but it is not working on Macbook M1). In case output has been generated from one of the previous runs the file will exist even if emtpy (if run with the old version), depending on the dir structure you are using this might explain the issue. Could you exit the cloned directory and run the following steps:
 mamba create -c conda-forge -c bioconda -n snk snakemake   # for testing purpose make sure the env only contains snakemake conda activate snk  # activate the env rm -rf gvclass # delete the old gvclass dir including the example dir and the hidden .snakemake dir git clone https://github.com/NeLLi-team/gvclass.git # clone it again cd gvclass # run the snakemake from within the cloned dir snakemake -j  8 --use-conda --config querydir="example"  # example command  
In case it still does not work please send me the "example/results" and the .snakemake/log dirs so that I can check the detailed output.
 
We are also working on a new docker version of gvclass and update the repo later this week which might solve any potential issue with snakemake.

**Comment by timeresistance1996** [comment]
I have sent the result file as an attachment. I wonder if you have receive it？

**Comment by fschjgi** [comment]
I did not receive the attachment, could you please send it to fschulz@lbl.gov or upload it to dropbox or google drive and share the link for download.
